name: Build HXCPP from Local Source

on:
  workflow_dispatch:

jobs:
  build-hxcpp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - run: haxelib setup ~/haxelib

      - run: |
          REPO=$(pwd)
          cd ${REPO}/tools/run
          haxe compile.hxml
          cd ${REPO}/tools/hxcpp
          haxe compile.hxml
          cd $REPO

      - run: |
          REPO=$(pwd)
          cd ${REPO}/project
          haxe compile-cppia.hxml
          cd $REPO

      - run: haxelib dev hxcpp .

      - uses: actions/upload-artifact@v4
        with:
          name: hxcpp-built
          path: .
